{
 "title": "New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Application Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Disk Space Free",
     "measurement": "app_health",
     "select": [
      [
       { "params": [ "diskSpace_free" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Disk Space Total",
     "measurement": "app_health",
     "select": [
      [
       { "params": [ "diskSpace_total" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Container Disk Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_stats_io_service_bytes_recursive_read",
     "legendFormat": "Disk Read"
    },
    {
     "expr": "docker_stats_io_service_bytes_recursive_write",
     "legendFormat": "Disk Write"
    }
   ]
  },
  {
   "title": "Application Health",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "app_health",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Container Health",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "docker_container_status_exitcode"
    }
   ]
  },
  {
   "title": "Default Logging Level",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "app_loggers",
     "select": [
      [
       { "params": [ "Default_effectiveLevel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Microsoft Logging Level",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "app_loggers",
     "select": [
      [
       { "params": [ "Microsoft_effectiveLevel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Steeltoe Logging Level",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "app_loggers",
     "select": [
      [
       { "params": [ "Steeltoe_effectiveLevel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(docker_container_cpu_usage_in_usermode[5m]) * 100)"
    }
   ]
  },
  {
   "title": "Container Logs",
   "type": "table",
   "gridPos": { "h": 30, "w": 9, "x": 0, "y": 11 },
   "targets": [
    {
     "measurement": "docker_log",
     "query": "SELECT \"message\" FROM \"docker_log\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "message" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Rx Tx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "docker_container_net_rx_bytes{network=\"total\"}  ",
     "legendFormat": "Rx Bytes"
    },
    {
     "expr": "docker_container_net_tx_bytes{network=\"total\"}",
     "legendFormat": "Tx Bytes"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(docker_container_mem_usage)/1024/1024",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum(docker_container_mem_limit)/1024/1024",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  {
   "title": "Application Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_request_count{method!=\"HEAD\",uri!~\"/actuators.*\",status=\"200\"}",
     "legendFormat": "{{status}} [{{method}}] [{{uri}}]"
    },
    {
     "expr": "http_server_request_count{method!=\"HEAD\",uri!~\"/actuators.*\",status=\"300\"}",
     "legendFormat": "{{status}} [{{method}}] [{{uri}}]"
    },
    {
     "expr": "http_server_request_count{method!=\"HEAD\",uri!~\"/actuators.*\",status=\"404\"}",
     "legendFormat": "{{status}} [{{method}}] [{{uri}}]"
    },
    {
     "expr": "http_server_request_count{method!=\"HEAD\",uri!~\"/actuators.*\",status=\"500\"}",
     "legendFormat": "{{status}} [{{method}}] [{{uri}}]"
    }
   ]
  }
 ]
}